### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Ranaghaas** [bayanwafa/MiniGamesWebsite#10]
I have a problem with my the style of my page. it used to be column but now now its all lined up in one line ?
![Screenshot](https://github.com/bayanwafa/MiniGamesWebsite/assets/145955263/08a59fb8-b334-4399-b47e-4f4364a0c6b4)

**Comment by bayanwafa** [comment]
You can put display:grid, center, and space-around. 
Should you put a description for the game and back arrow to the home page.

**Comment by Ranaghaas** [comment]
I did try your recommendations but still didnt work. its better now but still not what I want !
