### ISSUE TITLE
X and O description 

### ISSUE THREAD

**Issue by Ftoon-an** [bayanwafa/MiniGamesWebsite#11]
Hi guys,

I found an issue while I was doing a description for my game. In HTML, The font of the order list and the unordered list is bold. 
Also, the unordered list doesn't show the bullet points. 

You can check this in the picture below:
![Screenshot 2023-10-26 133930](https://github.com/bayanwafa/MiniGamesWebsite/assets/144382657/ef9cf2c5-70e0-461c-b443-aa29c36ad6f3)

**Comment by bayanwafa** [comment]
You can change color the list to this color #555;

**Comment by Ranaghaas** [comment]
I'd suggest to change the font-weight :normal

**Comment by Ftoon-an** [comment]
I have done that thanks for helping!
